# syntax=docker/dockerfile:1
FROM node:22-alpine as base

WORKDIR /usr/src/app
EXPOSE 3000

# Install dependencies (including dev ones)
COPY package*.json ./
RUN npm ci

# Copy source
COPY . .

# Use non-root user
RUN addgroup -S nodejs && adduser -S nextjs -G nodejs
USER nextjs

ENV NODE_ENV=development
CMD ["npm", "run", "dev"]
