import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@/styles/globals.css";
import "@/lib/orpc/orpc.server";

import { getServerSession } from "@/server/auth";
import { ORPCProvider } from "@/lib/orpc/provider";
import { getQueryClient, HydrateClient } from "@/lib/orpc/query/hydration";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/navbar/navbar";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  const queryClient = getQueryClient();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <body className="bg-background min-h-dvh font-sans antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex min-h-dvh flex-col">
            <Navbar session={session} />
            <ORPCProvider>
              <HydrateClient client={queryClient}>
                <main className="flex-1">{children}</main>
              </HydrateClient>
            </ORPCProvider>
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
